# Generated by Django 5.2.14 on 2026-06-05 07:25

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("type_key", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "travel_types",
            },
        ),
        migrations.CreateModel(
            name="UserTestResult",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("result_vector", pgvector.django.vector.VectorField(dimensions=6)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "travel_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="travel_quiz.traveltype"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "user_quiz_results",
                "unique_together": {("user",)},
            },
        ),
    ]
