# Generated by Django 5.2.14 on 2026-06-05 08:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_quiz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="traveltype",
            options={"verbose_name": "여행 성향 유형", "verbose_name_plural": "여행 성향 유형 목록"},
        ),
        migrations.AlterModelOptions(
            name="usertestresult",
            options={"verbose_name": "유저 여행 성향 테스트 결과", "verbose_name_plural": "유저 여행 성향 테스트 결과"},
        ),
    ]
