# Generated by Django 5.2.14 on 2026-06-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0009_alter_place_options_alter_placefeature_options_and_more"),
        ("travel_quiz", "0003_alter_usertestresult_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveltype",
            name="description",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="traveltype",
            name="image_url",
            field=models.URLField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="traveltype",
            name="tags",
            field=models.ManyToManyField(to="place.tag"),
        ),
        migrations.AlterField(
            model_name="traveltype",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="usertestresult",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
