# Generated by Django 5.2.14 on 2026-06-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_quiz", "0004_traveltype_description_traveltype_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveltype",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="traveltype",
            name="image_url",
            field=models.URLField(max_length=500),
        ),
    ]
