# Generated by Django 5.2.14 on 2026-06-08 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_quiz", "0005_alter_traveltype_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveltype",
            name="tags",
        ),
    ]
