# Generated by Django 5.2.14 on 2026-06-08 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travel_quiz", "0006_remove_traveltype_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="traveltype",
            name="description",
        ),
    ]
