# Generated by Django 5.2.14 on 2026-06-14 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_quiz", "0007_remove_traveltype_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertestresult",
            name="travel_type",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="travel_quiz.traveltype"),
        ),
    ]
