# Generated by Django 5.2.14 on 2026-06-05 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmark", "0001_initial"),
        ("place", "0009_alter_place_options_alter_placefeature_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={"ordering": ["-id"], "verbose_name": "북마크", "verbose_name_plural": "북마크 목록"},
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="북마크 일시"),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="place",
            field=models.ForeignKey(
                db_column="place_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="place.place",
                verbose_name="장소",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저",
            ),
        ),
    ]
