# Generated by Django 5.2.14 on 2026-06-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
