# Generated by Django 5.2.14 on 2026-06-05 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_review_image_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-id"]},
        ),
    ]
