# Generated by Django 5.2.14 on 2026-06-05 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0009_alter_place_options_alter_placefeature_options_and_more"),
        ("review", "0002_review_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-id"], "verbose_name": "리뷰", "verbose_name_plural": "리뷰 목록"},
        ),
        migrations.AlterField(
            model_name="review",
            name="content",
            field=models.TextField(max_length=200, verbose_name="내용"),
        ),
        migrations.AlterField(
            model_name="review",
            name="image_url",
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name="이미지 URL"),
        ),
        migrations.AlterField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="place.place",
                verbose_name="장소",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                verbose_name="별점",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="작성자",
            ),
        ),
    ]
