# Generated by Django 5.2.14 on 2026-06-05 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_merge_0003_migrations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-id"], "verbose_name": "리뷰", "verbose_name_plural": "리뷰 목록"},
        ),
    ]
