# Generated by Django 5.2.14 on 2026-06-08 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0004_merge_20260605_1852"),
        ("review", "0005_alter_review_options"),
    ]

    operations = []
