# Generated by Django 5.2.14 on 2026-06-12 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0005_alter_review_options"),
        ("route", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="route.route",
                verbose_name="연결된 경로",
            ),
        ),
    ]
