# Generated by Django 5.2.14 on 2026-06-12 09:30
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0006_merge_20260608_1402"),
        ("review", "0006_review_route"),
    ]
    operations = []
