# Generated by Django 5.2.14 on 2026-06-10 03:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("place", "0010_merge_0009_migrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=20, verbose_name="제목")),
                ("description", models.TextField(blank=True, null=True, verbose_name="설명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                ("like_count", models.PositiveIntegerField(default=0, verbose_name="좋아요 수")),
                (
                    "region_tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="region_routes",
                        to="place.tag",
                        verbose_name="지역 태그",
                    ),
                ),
                (
                    "theme_tags",
                    models.ManyToManyField(
                        blank=True, related_name="theme_routes", to="place.tag", verbose_name="테마 태그"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "경로",
                "verbose_name_plural": "경로 목록",
                "db_table": "routes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_index",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="일차",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="days",
                        to="route.route",
                        verbose_name="경로",
                    ),
                ),
            ],
            options={
                "verbose_name": "경로 일차",
                "verbose_name_plural": "경로 일차 목록",
                "db_table": "route_days",
                "ordering": ["day_index"],
            },
        ),
        migrations.CreateModel(
            name="RouteDayPlace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="순서",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="place.place", verbose_name="장소"
                    ),
                ),
                (
                    "route_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_places",
                        to="route.routeday",
                        verbose_name="일차",
                    ),
                ),
            ],
            options={
                "verbose_name": "경로 장소",
                "verbose_name_plural": "경로 장소 목록",
                "db_table": "route_day_places",
                "ordering": ["order"],
                "unique_together": {("route_day", "order")},
            },
        ),
        migrations.AddField(
            model_name="routeday",
            name="places",
            field=models.ManyToManyField(through="route.RouteDayPlace", to="place.place", verbose_name="장소"),
        ),
        migrations.AlterUniqueTogether(
            name="routeday",
            unique_together={("route", "day_index")},
        ),
        migrations.CreateModel(
            name="RouteLike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="좋아요 일시")),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="route.route",
                        verbose_name="경로",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "경로 좋아요",
                "verbose_name_plural": "경로 좋아요 목록",
                "db_table": "route_likes",
                "unique_together": {("route", "user")},
            },
        ),
    ]
