# Generated by Django 5.2.14 on 2026-06-22 05:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("route", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="routeday",
            name="day_index",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)],
                verbose_name="일차",
            ),
        ),
    ]
