# Generated by Django 5.2.14 on 2026-05-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("nickname", models.CharField(max_length=10, unique=True)),
                ("gender", models.CharField(choices=[("M", "남성"), ("F", "여성")], max_length=6, null=True)),
                ("birthday", models.DateField()),
                ("profile_img_url", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("role", models.CharField(choices=[("USER", "일반유저"), ("ADMIN", "관리자")], default="USER")),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("kakao", "카카오")], max_length=10)),
                ("provider_id", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="social_users", to="user.user"
                    ),
                ),
            ],
            options={
                "db_table": "social_users",
            },
        ),
    ]
