# Generated by Django 5.2.14 on 2026-06-02 02:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_nickname_max_length"),
        ("user", "0002_user_bio_alter_user_nickname_follow"),
    ]

    operations = []
