# Generated by Django 5.2.14 on 2026-06-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0002_alter_place_rating_avg"),
        ("user", "0003_merge_20260602_1155"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="users", to="place.tag"),
        ),
    ]
