# Generated by Django 5.2.14 on 2026-06-05 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0009_alter_place_options_alter_placefeature_options_and_more"),
        ("user", "0006_user_is_staff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={"verbose_name": "팔로우", "verbose_name_plural": "팔로우 목록"},
        ),
        migrations.AlterModelOptions(
            name="socialuser",
            options={"verbose_name": "소셜 유저", "verbose_name_plural": "소셜 유저 목록"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "유저", "verbose_name_plural": "유저 목록"},
        ),
        migrations.AlterField(
            model_name="follow",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="팔로우 일시"),
        ),
        migrations.AlterField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로워",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로잉",
            ),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(choices=[("kakao", "카카오")], max_length=10, verbose_name="제공자"),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="provider_id",
            field=models.CharField(max_length=255, verbose_name="제공자 ID"),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="유저",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="자기소개"),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="탈퇴 일시"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=255, unique=True, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "남성"), ("F", "여성")], max_length=6, null=True, verbose_name="성별"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="스태프 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(max_length=14, unique=True, verbose_name="닉네임"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img_url",
            field=models.CharField(blank=True, max_length=255, verbose_name="프로필 이미지 URL"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("USER", "일반유저"), ("ADMIN", "관리자")], default="USER", verbose_name="권한"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="users", to="place.tag", verbose_name="관심 태그"),
        ),
    ]
