# Generated by Django 5.2.14 on 2026-06-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0008_merge_user_migrations"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="socialuser",
            constraint=models.UniqueConstraint(fields=("provider", "provider_id"), name="unique_provider_account"),
        ),
    ]
