# Generated by Django 5.2.14 on 2026-06-15 05:35

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0015_place_view_count_placefeature_content_vector"),
        ("user", "0009_social_user_unique_provider_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_vector",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1024, null=True, verbose_name="행동 기반 임베딩 벡터"
                    ),
                ),
                ("action_count", models.PositiveIntegerField(default=0, verbose_name="누적 행동 수")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저 행동 선호",
                "verbose_name_plural": "유저 행동 선호 목록",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserActionLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("review", "리뷰"),
                            ("bookmark", "북마크"),
                            ("unbookmark", "북마크 해제"),
                            ("route_add", "경로 추가"),
                        ],
                        max_length=20,
                        verbose_name="행동 유형",
                    ),
                ),
                ("weight", models.FloatField(verbose_name="가중치")),
                ("processed", models.BooleanField(default=False, verbose_name="유저 벡터 반영 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="발생 일시")),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="place.place",
                        verbose_name="장소",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저",
                    ),
                ),
            ],
            options={
                "verbose_name": "유저 행동 로그",
                "verbose_name_plural": "유저 행동 로그 목록",
                "db_table": "user_action_logs",
                "indexes": [
                    models.Index(fields=["user", "place", "action_type"], name="useraction_user_place_type_idx"),
                    models.Index(
                        condition=models.Q(("processed", False)),
                        fields=["processed"],
                        name="useraction_unprocessed_idx",
                    ),
                ],
            },
        ),
    ]
