services:
  web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    image: mashiro2465/travel-maker-web:latest

  celery_worker:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    image: mashiro2465/travel-maker-celery-worker:latest

  celery_beat:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    image: mashiro2465/travel-maker-celery-beat:latest

  flower:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile
    image: mashiro2465/travel-maker-flower:latest
