# Generated by Django 5.2.14 on 2026-05-29 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("place_name", models.CharField(max_length=50)),
                ("latitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=7, max_digits=10)),
                ("rating_avg", models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "places",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag_type", models.CharField(max_length=20)),
                ("tag_name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlaceImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.CharField(default="default_image_url", max_length=255)),
                ("is_main", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="place.place"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="places", to="place.tag"),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(fields=["place_name"], name="places_place_n_ed1639_idx"),
        ),
    ]
