# Generated by Django 5.2.14 on 2026-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0002_alter_place_rating_avg"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placeimage",
            options={"ordering": ["order", "id"]},
        ),
        migrations.AddField(
            model_name="place",
            name="address_detail",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="address_primary",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="content_id",
            field=models.IntegerField(db_index=True, default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="content_type_id",
            field=models.PositiveSmallIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="place",
            name="homepage",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="lcls_systm1",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="lcls_systm2",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="lcls_systm3",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="tel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="placeimage",
            name="thumbnail_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name="place",
            name="place_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="image_url",
            field=models.CharField(max_length=500),
        ),
        migrations.AddConstraint(
            model_name="placeimage",
            constraint=models.UniqueConstraint(fields=("place", "image_url"), name="unique_place_image_url"),
        ),
    ]
