# Generated by Django 5.2.14 on 2026-06-02 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0004_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operating_hours", models.TextField(blank=True, null=True)),
                ("closed_days", models.TextField(blank=True, null=True)),
                ("parking", models.BooleanField(null=True)),
                ("admission_fee", models.TextField(blank=True, null=True)),
                ("spend_time", models.CharField(blank=True, max_length=50, null=True)),
                ("discount_info", models.TextField(blank=True, null=True)),
                ("accom_count", models.CharField(blank=True, max_length=50, null=True)),
                ("pet", models.BooleanField(null=True)),
                ("baby_carriage", models.BooleanField(null=True)),
                ("credit_card", models.BooleanField(null=True)),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="info", to="place.place"
                    ),
                ),
            ],
            options={
                "db_table": "place_info",
            },
        ),
    ]
