# Generated by Django 5.2.14 on 2026-06-02 08:29

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0005_placeinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("style_vector", pgvector.django.vector.VectorField(dimensions=6)),
                (
                    "place",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="place_feature", to="place.place"
                    ),
                ),
            ],
            options={
                "db_table": "place_features",
            },
        ),
    ]
