# Generated by Django 5.2.14 on 2026-06-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0006_placefeature"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="place",
            name="source_modified_at",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True),
        ),
    ]
