# Generated by Django 5.2.14 on 2026-06-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0007_place_is_active_place_source_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeinfo",
            name="accom_count",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="spend_time",
            field=models.TextField(blank=True, null=True),
        ),
    ]
