# Generated by Django 5.2.14 on 2026-06-05 08:01

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0008_alter_placeinfo_accom_count_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"verbose_name": "장소", "verbose_name_plural": "장소 목록"},
        ),
        migrations.AlterModelOptions(
            name="placefeature",
            options={"verbose_name": "장소 성향 벡터", "verbose_name_plural": "장소 성향 벡터 목록"},
        ),
        migrations.AlterModelOptions(
            name="placeimage",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "장소 이미지",
                "verbose_name_plural": "장소 이미지 목록",
            },
        ),
        migrations.AlterModelOptions(
            name="placeinfo",
            options={"verbose_name": "장소 운영정보", "verbose_name_plural": "장소 운영정보 목록"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "태그", "verbose_name_plural": "태그 목록"},
        ),
        migrations.AlterField(
            model_name="place",
            name="address_detail",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="상세 주소"),
        ),
        migrations.AlterField(
            model_name="place",
            name="address_primary",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="주소"),
        ),
        migrations.AlterField(
            model_name="place",
            name="content_id",
            field=models.IntegerField(db_index=True, unique=True, verbose_name="Tour API 콘텐츠 ID"),
        ),
        migrations.AlterField(
            model_name="place",
            name="content_type_id",
            field=models.PositiveSmallIntegerField(db_index=True, verbose_name="관광 타입 ID"),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="설명"),
        ),
        migrations.AlterField(
            model_name="place",
            name="homepage",
            field=models.TextField(blank=True, null=True, verbose_name="홈페이지"),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True, verbose_name="활성 여부"),
        ),
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name="위도"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lcls_systm1",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name="분류 대분류"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lcls_systm2",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name="분류 중분류"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lcls_systm3",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name="분류 소분류"),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name="경도"),
        ),
        migrations.AlterField(
            model_name="place",
            name="place_name",
            field=models.CharField(max_length=100, verbose_name="장소명"),
        ),
        migrations.AlterField(
            model_name="place",
            name="rating_avg",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, verbose_name="평균 별점"),
        ),
        migrations.AlterField(
            model_name="place",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="평점 수"),
        ),
        migrations.AlterField(
            model_name="place",
            name="source_modified_at",
            field=models.CharField(blank=True, db_index=True, max_length=14, null=True, verbose_name="원본 수정 일시"),
        ),
        migrations.AlterField(
            model_name="place",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="places", to="place.tag", verbose_name="태그"),
        ),
        migrations.AlterField(
            model_name="place",
            name="tel",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="전화번호"),
        ),
        migrations.AlterField(
            model_name="place",
            name="zipcode",
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="우편번호"),
        ),
        migrations.AlterField(
            model_name="placefeature",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="place_feature",
                to="place.place",
                verbose_name="장소",
            ),
        ),
        migrations.AlterField(
            model_name="placefeature",
            name="style_vector",
            field=pgvector.django.vector.VectorField(dimensions=6, verbose_name="성향 벡터"),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="image_url",
            field=models.CharField(max_length=500, verbose_name="이미지 URL"),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="is_main",
            field=models.BooleanField(default=False, verbose_name="대표 이미지 여부"),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="순서"),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="place.place",
                verbose_name="장소",
            ),
        ),
        migrations.AlterField(
            model_name="placeimage",
            name="thumbnail_url",
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="썸네일 URL"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="accom_count",
            field=models.TextField(blank=True, null=True, verbose_name="수용 인원"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="admission_fee",
            field=models.TextField(blank=True, null=True, verbose_name="입장료"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="baby_carriage",
            field=models.BooleanField(null=True, verbose_name="유모차 동반 가능"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="closed_days",
            field=models.TextField(blank=True, null=True, verbose_name="휴무일"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="credit_card",
            field=models.BooleanField(null=True, verbose_name="카드 결제 가능"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="discount_info",
            field=models.TextField(blank=True, null=True, verbose_name="할인 정보"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="operating_hours",
            field=models.TextField(blank=True, null=True, verbose_name="운영시간"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="parking",
            field=models.BooleanField(null=True, verbose_name="주차 가능 여부"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="pet",
            field=models.BooleanField(null=True, verbose_name="반려동물 동반 가능"),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="info", to="place.place", verbose_name="장소"
            ),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="spend_time",
            field=models.TextField(blank=True, null=True, verbose_name="관람 소요시간"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_name",
            field=models.CharField(max_length=20, unique=True, verbose_name="태그명"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(max_length=20, verbose_name="태그 유형"),
        ),
    ]
