# Generated by Django 5.2.14 on 2026-06-05 04:28

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0008_alter_placeinfo_accom_count_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="placefeature",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["style_vector"],
                m=16,
                name="place_style_vector_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
