# Generated by Django 5.2.14 on 2026-06-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0010_merge_0009_migrations"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                condition=models.Q(("is_active", True)), fields=["-rating_avg", "-id"], name="place_active_rating_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                condition=models.Q(("is_active", True)), fields=["-rating_count", "-id"], name="place_active_review_idx"
            ),
        ),
    ]
