# Generated by Django 5.2.14 on 2026-06-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0011_place_place_active_rating_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placefeature",
            name="id",
        ),
        migrations.RemoveField(
            model_name="placeinfo",
            name="id",
        ),
        migrations.AlterField(
            model_name="place",
            name="content_id",
            field=models.IntegerField(unique=True, verbose_name="Tour API 콘텐츠 ID"),
        ),
        migrations.AlterField(
            model_name="place",
            name="content_type_id",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (12, "관광지"),
                    (14, "문화시설"),
                    (15, "축제공연행사"),
                    (25, "여행코스"),
                    (28, "레포츠"),
                    (32, "숙박"),
                    (38, "쇼핑"),
                    (39, "음식점"),
                ],
                db_index=True,
                verbose_name="관광 타입 ID",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="활성 여부"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lcls_systm1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NA", "자연관광"),
                    ("HS", "역사관광"),
                    ("VE", "문화관광"),
                    ("EV", "축제/공연/행사"),
                    ("EX", "체험관광"),
                    ("LS", "레저스포츠"),
                    ("AC", "숙박"),
                    ("SH", "쇼핑"),
                    ("FD", "음식"),
                ],
                max_length=20,
                null=True,
                verbose_name="분류 대분류",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="lcls_systm2",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="분류 중분류"),
        ),
        migrations.AlterField(
            model_name="place",
            name="lcls_systm3",
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="분류 소분류"),
        ),
        migrations.AlterField(
            model_name="place",
            name="source_modified_at",
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name="원본 수정 일시"),
        ),
        migrations.AlterField(
            model_name="placefeature",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="place_feature",
                serialize=False,
                to="place.place",
                verbose_name="장소",
            ),
        ),
        migrations.AlterField(
            model_name="placeinfo",
            name="place",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="info",
                serialize=False,
                to="place.place",
                verbose_name="장소",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag_type",
            field=models.CharField(
                choices=[
                    ("여행 스타일", "여행 스타일"),
                    ("세부 테마", "세부 테마"),
                    ("동행", "동행"),
                    ("지역", "지역"),
                    ("편의성", "편의성"),
                ],
                max_length=20,
                verbose_name="태그 유형",
            ),
        ),
    ]
