# Generated by Django 5.2.14 on 2026-06-15 05:35

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0014_place_name_trgm_gin_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
        migrations.AddField(
            model_name="placefeature",
            name="content_vector",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1024, null=True, verbose_name="텍스트 임베딩 벡터"
            ),
        ),
    ]
