# Generated by Django 5.2.14 on 2026-06-15 05:56

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0015_place_view_count_placefeature_content_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="placefeature",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["content_vector"],
                m=16,
                name="place_content_vector_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
