# Generated by Django 5.2.14 on 2026-06-15 07:50

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("place", "0016_placefeature_place_content_vector_hnsw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placefeature",
            name="style_vector",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=6, null=True, verbose_name="성향 벡터"),
        ),
    ]
